language: python
python:
    - '2.7'
before_install:
    - pip install codecov
install:
    - pip install --upgrade pytest numpy netCDF4
env:
  global:
    - PYTHONPATH=$PYTHONPATH:..:.
script:
    - py.test
after_success:
    - coverage run --source=n2nc,nc_compress,test/test_nc2nc.py,test/test_nc_compress.py -m py.test
    - codecov
